# Production
services:
  guacd:
    image: guacamole/guacd
    platform: linux/amd64
    container_name: guacd
    restart: always
    volumes:
      - ./guacamole/recordings:/var/lib/guacamole/recordings:rw
      - ./guacamole/drive:/drive:rw
    ports:
      - "4822:4822"
    networks:
      - node-network 
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: guac_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: guacamole_root_pw
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_user_pw
    volumes:
      - guacamole_db:/var/lib/mysql
      - ./guacamole/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - node-network 
  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    platform: linux/amd64
    restart: always
    depends_on:
      - guacd
      - mysql
    environment:
      GUACAMOLE_HOME: '/opt/guacamole_home'
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_user_pw
      GUACAMOLE_CORS_ENABLED: 'true'
      GUACAMOLE_CORS_ALLOWED_ORIGINS: '*'
      GUACAMOLE_CORS_ALLOWED_METHODS: 'GET, POST, PUT, DELETE, OPTIONS'
    ports:
      - "8080:8080"
    volumes:
      - ./guacamole/home:/opt/guacamole_home
      - ./guacamole/recordings:/var/lib/guacamole/recordings:rw
      - ./guacamole/drive:/drive:rw
    links:
      - guacd
      - mysql
    networks:
      - node-network 

  back-end:
    build:
      context: backend
    container_name: back-end
    working_dir: /usr/src/app/backend
    networks:
      - node-network
    tty: true
    ports:
      - "8001:8001"
    # command: npm start
    command: sh -c "npm run build && export NODE_OPTIONS=--openssl-legacy-provider && node build/server.js"
    volumes:
      - ./backend/public/screenshots:/usr/src/app/backend/public/screenshots
      - ./guacamole/recordings:/var/lib/guacamole/recordings:rw
    environment:
      - DB_URI=${DB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPEN_AI_SECRET=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - RPC_URL=${RPC_URL}
      - IPC_SECRET=${IPC_SECRET}
      - ANCHOR_PROVIDER_URL=${ANCHOR_PROVIDER_URL}
      # Docker Specific Paths
      - ANCHOR_WALLET=/usr/src/app/backend/secrets/solana-keypair.json
      - ANCHOR_WORKSPACE=/usr/src/app/backend/jailbreak-pool
      # VNC Configuration
      - VNC_HOST=windows
      - VNC_PORT=5900
      - VNC_PASSWORD=admin
      - SERVICE_HOST=windows
      - SERVICE_PORT=6950
      - GYM_TREASURY_WALLET=${GYM_TREASURY_WALLET}
      - GYM_TREASURY_WEBHOOK=${GYM_TREASURY_WEBHOOK}
      - VIRAL_TOKEN=${VIRAL_TOKEN}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - GUACAMOLE_PASSWORD=${GUACAMOLE_PASSWORD}
    depends_on:
      - mongodb
      # - windows
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - node-network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  front-end:
    build:
      context: frontend
    container_name: front-end
    working_dir: /usr/src/app/frontend
    networks:
      - node-network
    tty: true
    ports:
      - "5173:5173"
    command: sh -c "npm run build && npm run preview -- --host 0.0.0.0 --port 5173"

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "80:80"
    networks:
      - node-network
    depends_on:
      - back-end
      - front-end

networks:
  node-network:
    driver: bridge

volumes:
  mongodb_data:
  guacamole_db:

