[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
jailbreak_pool = "ERj3jW3GAY26GR8KU5cfmSB8yzDwCer9X3q8n9sZ3iqW"

[programs.localnet]
jailbreak_pool = "ERj3jW3GAY26GR8KU5cfmSB8yzDwCer9X3q8n9sZ3iqW"

[programs.mainnet]
jailbreak_pool = "ERj3jW3GAY26GR8KU5cfmSB8yzDwCer9X3q8n9sZ3iqW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./secrets/solana-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
