FROM node:21.4.0-bookworm

WORKDIR /usr/src/app/backend/

COPY package*.json ./
COPY jailbreak-pool/Anchor.toml ./
COPY jailbreak-pool/target ./target

# Install dependencies including guacamole build requirements
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    python3 \
    ffmpeg \
    autoconf \
    libtool \
    libcairo2-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libossp-uuid-dev \
    libavcodec-dev \
    libavformat-dev \
    libavutil-dev \
    libswscale-dev \
    freerdp2-dev \
    libpango1.0-dev \
    libssh2-1-dev \
    libtelnet-dev \
    libvncserver-dev \
    libwebsockets-dev \
    libpulse-dev \
    libssl-dev \
    libvorbis-dev \
    libwebp-dev \
    git && \
    git clone https://github.com/apache/guacamole-server.git && \
    cd guacamole-server && \
    autoreconf -fi && \
    ./configure --with-init-dir=/etc/init.d && \
    make && \
    make install && \
    ldconfig && \
    cd .. && \
    rm -rf guacamole-server && \
    apt-get remove -y git autoconf libtool && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

RUN npm install

COPY . .

EXPOSE 8001